name: Push Docker Image

on:
  push:
    branches:
      - traP
      - traP-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set DRONE_TAG env (non traP branch)
        run: echo ::set-env name=DRONE_TAG::$(echo ${GITHUB_REF:11})
        if: github.ref != 'refs/heads/traP'
      - name: Set DRONE_TAG env (traP branch)
        run: echo ::set-env name=DRONE_TAG::$(echo $GITHUB_SHA)
        if: github.ref == 'refs/heads/traP'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Make Release
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/monkeyWie/xgo
          make release
        env:
          TAGS: bindata sqlite sqlite_unlock_notify
      - name: Release
        uses: fnkr/github-action-ghr@bc9a9ecae3c0c6cbc71a96390e344171f963d59d
        env:
          GHR_PATH: dist/release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ join('refs/tags/', env.DRONE_TAG) }}
