name: Push Docker Image

on:
  push:
    tags:
      - traP-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: techknowlogick/xgo:latest
    steps:
      - name: Set DRONE_TAG env
        run: echo ::set-env name=DRONE_TAG::$(echo ${GITHUB_REF:10})
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Make Release
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make release
        env:
          GOPROXY: off
          TAGS: bindata sqlite sqlite_unlock_notify
      - name: Release
        uses: fnkr/github-action-ghr@bc9a9ecae3c0c6cbc71a96390e344171f963d59d
        env:
          GHR_PATH: dist/release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release binaries
        uses: fnkr/github-action-ghr@bc9a9ecae3c0c6cbc71a96390e344171f963d59d
        env:
          GHR_PATH: dist/binaries
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
